// lib/json-export.js
// Structured JSON export with optional filtering & cleanup

export function generateJSON(data, opts = {}) {
  const { pretty = true, minify = false, omitKeys = [], maxDepth = Infinity } = opts;

  // Deep clone & sanitize (remove circular refs, functions, undefined)
  const cleaned = sanitize(data, omitKeys, maxDepth);

  return minify
    ? JSON.stringify(cleaned)
    : JSON.stringify(cleaned, null, pretty ? 2 : 0);
}

// ─────────────────────────────────────────────────────────
// Sanitizer — removes non-serializable & circular refs
// ─────────────────────────────────────────────────────────
function sanitize(value, omitKeys = [], maxDepth = Infinity, depth = 0, seen = new WeakSet()) {
  if (depth > maxDepth) return '[max-depth]';
  if (value === null || value === undefined) return value;
  if (typeof value === 'function') return `[Function: ${value.name || 'anonymous'}]`;
  if (typeof value === 'symbol') return value.toString();
  if (typeof value === 'bigint') return value.toString() + 'n';

  // Primitives
  if (typeof value !== 'object') return value;

  // Detect circular
  if (seen.has(value)) return '[Circular]';
  seen.add(value);

  // DOM nodes (shouldn't happen post-extraction, but safety)
  if (value instanceof Node) return `[${value.constructor.name}]`;
  if (value instanceof Error) return { error: value.message, stack: value.stack };

  // Arrays
  if (Array.isArray(value)) {
    return value.map(v => sanitize(v, omitKeys, maxDepth, depth + 1, seen));
  }

  // Objects
  const out = {};
  for (const key of Object.keys(value)) {
    if (omitKeys.includes(key)) continue;
    try {
      out[key] = sanitize(value[key], omitKeys, maxDepth, depth + 1, seen);
    } catch (e) {
      out[key] = `[Unserializable: ${e.message}]`;
    }
  }
  return out;
}

// ─────────────────────────────────────────────────────────
// Compact summary (useful for AI/LLM consumption)
// ─────────────────────────────────────────────────────────
export function generateSummaryJSON(data) {
  return JSON.stringify({
    meta: data.meta,
    palette: data.layout?.palette?.slice(0, 20),
    designTokens: data.css?.variables,
    typography: {
      base: data.typography?.base,
      scaleCount: data.typography?.scale?.length,
    },
    libraries: data.scriptIntel?.libraries || [],
    animations: {
      gsapTweens: data.runtime?.gsap?.tweens?.length || 0,
      gsapTimelines: data.runtime?.gsap?.timelines?.length || 0,
      scrollTriggers: data.runtime?.scrollTriggers?.length || 0,
      cssKeyframes: Object.keys(data.css?.keyframes || {}).length,
      lottieCount: data.runtime?.lottie?.length || 0,
      threeCount: data.runtime?.three?.length || 0,
    },
    interactions: {
      hover: data.interactions?.hover?.length || 0,
      focus: (data.interactions?.focus?.length || 0) + (data.interactions?.focusVisible?.length || 0),
      customCursors: data.interactions?.customCursors?.length || 0,
      magnetic: data.interactions?.magneticElements?.length || 0,
      parallax: data.interactions?.parallaxElements?.length || 0,
    },
    layout: {
      sections: data.layout?.tree?.length || 0,
      stickyEls: data.layout?.stickyEls?.length || 0,
      scrollContainers: data.layout?.scrollContainers?.length || 0,
      fingerprints: data.layout?.fingerprints?.length || 0,
      zLayers: data.layout?.zLayers?.length || 0,
    },
    assets: {
      images: data.assets?.images?.length || 0,
      videos: data.assets?.videos?.length || 0,
      fonts: data.assets?.fonts?.length || 0,
      bgImages: data.assets?.backgroundImages?.length || 0,
    },
    a11y: data.a11y,
    performance: data.performance,
    tailwind: data.tailwind?.likely ? {
      utilityCount: data.tailwind.utilityClassCount,
      breakpoints: data.tailwind.breakpointPrefixes,
      darkMode: data.tailwind.darkModeUsed,
    } : null,
  }, null, 2);
}

// ─────────────────────────────────────────────────────────
// CSS-only export (extracts a usable stylesheet)
// ─────────────────────────────────────────────────────────
export function generateCSSExport(data) {
  let css = `/* Generated by Design DNA — ${data.meta?.url} */\n\n`;

  // Variables
  if (data.css?.variables) {
    css += `:root {\n`;
    Object.entries(data.css.variables).forEach(([k, v]) => {
      css += `  ${k}: ${v};\n`;
    });
    css += `}\n\n`;
  }

  // @property
  if (data.css?.properties?.length) {
    data.css.properties.forEach(p => {
      css += `@property ${p.name} {\n  syntax: "${p.syntax || '*'}";\n  inherits: ${p.inherits};\n  initial-value: ${p.initialValue || ''};\n}\n\n`;
    });
  }

  // @font-face
  if (data.css?.fontFace?.length) {
    data.css.fontFace.forEach(ff => { css += ff + '\n\n'; });
  }

  // Keyframes
  if (data.css?.keyframes) {
    Object.values(data.css.keyframes).forEach(kf => { css += kf + '\n\n'; });
  }

  // Hover/focus rules
  if (data.interactions) {
    ['hover', 'focusVisible', 'focus', 'active'].forEach(state => {
      const rules = data.interactions[state];
      if (rules?.length) {
        css += `/* :${state.replace('Visible', '-visible')} */\n`;
        rules.forEach(r => {
          css += `${r.selector} { ${r.css} }\n`;
        });
        css += '\n';
      }
    });
  }

  return css;
}

// ─────────────────────────────────────────────────────────
// Tokens-only (Style Dictionary / Figma format)
// ─────────────────────────────────────────────────────────
export function generateDesignTokensJSON(data) {
  const tokens = {
    color: {},
    spacing: {},
    typography: {},
    radius: {},
    shadow: {},
    animation: {},
  };

  // Colors from palette
  data.layout?.palette?.slice(0, 30).forEach((p, i) => {
    tokens.color[`palette-${i + 1}`] = { value: p.color, usage: p.count };
  });

  // From CSS variables — categorize by name
  Object.entries(data.css?.variables || {}).forEach(([key, value]) => {
    const k = key.replace(/^--/, '');
    if (/color|bg|fg|text|border|fill|stroke/i.test(k)) tokens.color[k] = { value };
    else if (/space|gap|pad|margin|size/i.test(k)) tokens.spacing[k] = { value };
    else if (/font|text|line/i.test(k)) tokens.typography[k] = { value };
        else if (/radius|round/i.test(k)) tokens.radius[k] = { value };
    else if (/shadow|elevation/i.test(k)) tokens.shadow[k] = { value };
    else if (/duration|delay|ease|timing/i.test(k)) tokens.animation[k] = { value };
    else {
      // Catch-all — group by first segment
      const group = k.split(/[-_]/)[0];
      if (!tokens[group]) tokens[group] = {};
      tokens[group][k] = { value };
    }
  });

  // Typography from scale
  data.typography?.scale?.forEach((t, i) => {
    tokens.typography[`${t.tag}-${i}`] = {
      value: {
        fontFamily: t.fontFamily,
        fontSize: t.fontSize,
        fontWeight: t.fontWeight,
        lineHeight: t.lineHeight,
        letterSpacing: t.letterSpacing,
      },
    };
  });

  // Shadows mined from layout tree
  const shadows = new Set();
  const walk = (node) => {
    if (!node) return;
    if (node.visual?.boxShadow) shadows.add(node.visual.boxShadow);
    node.children?.forEach(walk);
  };
  data.layout?.tree?.forEach(walk);
  [...shadows].slice(0, 15).forEach((s, i) => {
    tokens.shadow[`shadow-${i + 1}`] = { value: s };
  });

  return JSON.stringify(tokens, null, 2);
}

// ─────────────────────────────────────────────────────────
// Tailwind config export (best-effort inference)
// ─────────────────────────────────────────────────────────
export function generateTailwindConfig(data) {
  const config = {
    theme: {
      extend: {
        colors: {},
        fontFamily: {},
        fontSize: {},
        spacing: {},
        borderRadius: {},
        boxShadow: {},
        screens: {},
      },
    },
  };

  // Colors
  data.layout?.palette?.slice(0, 20).forEach((p, i) => {
    const hex = rgbToHex(p.color);
    if (hex) config.theme.extend.colors[`brand-${i + 1}`] = hex;
  });

  // Fonts
  const fonts = new Set();
  data.typography?.scale?.forEach(t => fonts.add(t.fontFamily));
  [...fonts].forEach((f, i) => {
    const key = f.toLowerCase().replace(/\s+/g, '-');
    config.theme.extend.fontFamily[key] = [f, 'sans-serif'];
  });

  // Breakpoints from media queries
  const breakpoints = {};
  data.css?.mediaQueries?.forEach(mq => {
    const min = mq.condition?.match(/min-width:\s*(\d+)px/);
    if (min) breakpoints[`bp-${min[1]}`] = `${min[1]}px`;
  });
  config.theme.extend.screens = breakpoints;

  return `// Auto-generated from ${data.meta?.url}\n/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(config, null, 2)};\n`;
}

function rgbToHex(rgb) {
  if (!rgb) return null;
  if (rgb.startsWith('#')) return rgb;
  const m = rgb.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
  if (!m) return null;
  return '#' + [m[1], m[2], m[3]].map(n => parseInt(n).toString(16).padStart(2, '0')).join('');
}